export const listadeTarefas = [
    {id: 1, nome: "Fazer TCC", descricao: "começar os documentos do TCC", status: "Finalizado"},
    {id: 2, nome: "Comprar Roupas", descricao: "Comprar roupas online no site", status:"Em aberto"},
    {id: 3, nome: "Estudar React", descricao: "Ver o curso da full stack Club", status:"Finalizado"},
    {id: 4, nome: "Descansar", descricao: "Pausa para recuperar as energias", status:"Em aberto"},
    {id: 5, nome: "Assistir Naruto", descricao: "Ver episódios da fase Shippuden", status:"Em aberto"},
    {id: 6, nome: "Treinar Pernas", descricao: "Ir à academia fazer o treino B", status: "Em aberto"},
    {id: 7, nome: "Revisar Pull Requests", descricao: "Analisar o código da equipe no GitHub", status: "Em aberto"},
    {id: 8, nome: "Lavar o Carro", descricao: "Levar no posto ou lavar na garagem", status: "Finalizado"},
    {id: 9, nome: "Organizar Mesa", descricao: "Limpar setup e organizar cabos", status: "Em aberto"},
    {id: 10, nome: "Ler Livro Tecnológico", descricao: "Ler 10 páginas de 'Código Limpo'", status: "Finalizado"},
    {id: 11, nome: "Treino de Reabilitação", descricao: "Treino de reabilitação do joelho com carga", status: "Finalizado"},
    {id: 12, nome: "Soneca pós almoço", descricao: "Soneca naquele sofazinho do Allamo", status: "Finalizado"},
    {id: 13, nome: "Jogar Futebol as 11", descricao: "descrição da tarefa", status: "Finalizado"},
    {id: 14, nome: "Ir a consulta médica", descricao: "Descrição da tarefa", status: "Em andamento"},
    {id: 15, nome: "Platinar The Witcher 3", descricao: "Descrição da tarefa", status: "Em andamento"},
    {id: 16, nome: "Termianer módulo de tarefas", descricao: "Descrição da tarefa", status: "Em andamento"},
    {id: 17, nome: "Terminar Tarefa de KanBan", descricao: "Descrição da tarefa", status: "Em andamento"},
    {id: 18, nome: "Revisar Conteúdos aprendidos", descricao: "Descrição da tarefa", status: "Em andamento"},
    {id: 19, nome: "Estudar JavaScript", descricao: "Descrição da tarefa", status: "Em andamento"},
    {id: 20, nome: "Estudar React", descricao: "Descrição da tarefa", status: "Em andamento"},

];
